[package]
name = "atomic_enum"
version = "0.1.1"
authors = ["Thomas Bächler <thomas@archlinux.org>"]
edition = "2018"

description = "An attribute to create an atomic wrapper around a C-style enum"
repository = "https://github.com/brain0/atomic_enum"
keywords = ["atomic", "enum"]
categories = ["concurrency"]
license = "MIT"

[badges]
maintenance = { status = "passively-maintained" }

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"
syn = { version = "0.15", features=["full"] }
